name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-pipeline
  cancel-in-progress: false

jobs:
  qa:
    uses: ./.github/workflows/_build_and_test.yml
    with:
      ref: ${{ github.sha }}
      py_build: "3.14"
      py_test: '["3.11","3.12","3.13","3.14"]'
      coverage: false